# Generated by Django 6.0.3 on 2026-05-02 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('account_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_Name', models.CharField(max_length=50)),
                ('pin_Number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('customer_Age', models.IntegerField()),
                ('mobile_Number', models.IntegerField()),
                ('customer_Aadhaar', models.IntegerField()),
                ('customer_Address', models.CharField(max_length=200)),
                ('customer_State', models.CharField(max_length=100)),
            ],
        ),
    ]
