# Generated by Django 6.0.3 on 2026-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appATM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='balanceAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
