# Generated by Django 6.0.3 on 2026-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appATM', '0007_alter_customeraccount_balanceamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='balanceAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=29),
        ),
    ]
