# Generated by Django 6.0.3 on 2026-05-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appATM', '0008_alter_customeraccount_balanceamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='balanceAmount',
        ),
    ]
